# ---------- Stage 1: Build ----------
FROM maven:3.9.5-eclipse-temurin-21-alpine AS build
WORKDIR /opt
COPY . .
RUN mvn clean package -DskipTests

# ---------- Stage 2: Runtime ----------
FROM eclipse-temurin:17-jre-alpine

# Create non-root user
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

WORKDIR /app

# Copy jar
COPY --from=build /opt/target/*.jar app.jar

# Secure permissions
RUN chown appuser:appgroup app.jar && chmod 500 app.jar

# Switch user
USER appuser

EXPOSE 8081

ENTRYPOINT ["java","-jar","/app/app.jar"]

